# application.yml 与 application.properties 都可以作为配置文件，现在更加推荐使用 yml 文件。
# application.yml 在任何环境下都会生效。

# 在这里指定那个配置生效，在打完包之后，也可以通过命令指定，比如：java -jar xxx.jar --spring.profiles.active=dev
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none #不让 JPA 自己创建数据表。
  jackson:
    property-naming-strategy: SNAKE_CASE # json 序列化时，字段使用下划线方式命名。
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true # json 序列化时，时间序列化为时间戳。

# 放 api 实现的包
sleeve:
  api-package: com.lin.sleeve.api
  year-codes: A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z