# dev 文件只在 dev 环境下生效。文件的位置只要在 resources 下即可，但是必须以 application- 开头。
# 端口号
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleeve-official?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 201314
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    localhost: localhost
    port: 6379
    database: 7
    listen-pattern: __keyevent@7__:expired

rocketmq:
  producer:
    producer-group: SleeveProducerGroup
  consumer:
    producer-group: SleeveConsumerGroup
  namesrv-addr: 127.0.0.1:9876

sleeve:
  # jwt 令牌配置
  security:
    jwt-key: 7777777yue
    token-expired-in: 86400000
  # 订单最大数量，支付回调配置。
  order:
    max-sku-limit: 999
    pay-time-limit: 3600
    pay-callback-host: http://talelin.com
    pay-callback-path: /v1/payment/wx/notify
